services:
  servicoproposta:
    image: nawszera/propostams
    build: ./Proposta-app-/proposta-app
    restart: always
    environment:
      APP_PROFILE: test
      DB_URL: jdbc:postgresql://db:5432/propostadb
      DB_USERNAME: postgres
      DB_PASSWORD: 1234567
      HOST_RABBIT: rabbit
      PORT_RABBIT: 5672
    ports:
      - "8080:8080"
    depends_on:
      - rabbit
      - db
    networks:
      - naws-net
  servicoanalise:
    image: nawszera/analisems
    build: ./Analise-credito-app/analisecredito
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - rabbit
    networks:
      - naws-net
  db:
    image: postgres:16-alpine
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_DB: propostadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5433:5432"
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - naws-net
  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./.data/rabbitmq:/var/lib/rabbitmq
    networks:
      - naws-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    restart: always
    environment:
      TZ: America/Sao_Paulo
      PGADMIN_DEFAULT_EMAIL: me@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
    ports:
      - "5050:80"
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - naws-net


networks:
  naws-net:
    driver: bridge